/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WPPublisherPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/wordpress-client.ts
var import_obsidian = require("obsidian");
var WordPressClient = class {
  constructor(credentials) {
    this.credentials = credentials;
    this.authHeader = "Basic " + btoa(`${credentials.username}:${credentials.applicationPassword}`);
  }
  /**
   * Get the base API URL
   */
  getApiUrl(endpoint) {
    const baseUrl = this.credentials.siteUrl.replace(/\/$/, "");
    return `${baseUrl}/wp-json/wp/v2/${endpoint}`;
  }
  /**
   * Make an authenticated request to WordPress
   */
  async request(endpoint, options = {}) {
    const url = this.getApiUrl(endpoint);
    console.log("WP Publisher - Request:", {
      url,
      method: options.method || "GET",
      body: options.body ? JSON.parse(options.body) : void 0
    });
    const requestOptions = {
      url,
      method: options.method || "GET",
      headers: {
        "Authorization": this.authHeader,
        "Content-Type": "application/json",
        "Accept": "application/json",
        ...options.headers
      },
      throw: false
    };
    if (options.body && (options.method === "POST" || options.method === "PUT")) {
      requestOptions.body = options.body;
      requestOptions.contentType = "application/json";
    }
    const response = await (0, import_obsidian.requestUrl)(requestOptions);
    console.log("WP Publisher - Response status:", response.status);
    console.log("WP Publisher - Response body:", response.json);
    if (response.status >= 400) {
      const errorData = response.json;
      console.error("WP Publisher - API Error:", {
        status: response.status,
        error: errorData
      });
      throw new Error((errorData == null ? void 0 : errorData.message) || `HTTP ${response.status}: Request failed`);
    }
    return response.json;
  }
  /**
   * Test connection to WordPress site
   */
  async testConnection() {
    try {
      const user = await this.request("users/me");
      return {
        success: true,
        message: `Connected as ${user.name}`,
        user
      };
    } catch (error) {
      return {
        success: false,
        message: error instanceof Error ? error.message : "Connection failed"
      };
    }
  }
  /**
   * Get all categories
   */
  async getCategories() {
    return this.request("categories?per_page=100");
  }
  /**
   * Get all tags
   */
  async getTags() {
    return this.request("tags?per_page=100");
  }
  /**
   * Create or get a category by name
   */
  async getOrCreateCategory(name) {
    const categories = await this.getCategories();
    const existing = categories.find((c) => c.name.toLowerCase() === name.toLowerCase());
    if (existing) {
      return existing;
    }
    return this.request("categories", {
      method: "POST",
      body: JSON.stringify({ name })
    });
  }
  /**
   * Create or get a tag by name
   */
  async getOrCreateTag(name) {
    const tags = await this.getTags();
    const existing = tags.find((t) => t.name.toLowerCase() === name.toLowerCase());
    if (existing) {
      return existing;
    }
    return this.request("tags", {
      method: "POST",
      body: JSON.stringify({ name })
    });
  }
  /**
   * Create a new post or page
   */
  async createPost(post) {
    var _a;
    try {
      const endpoint = post.type === "page" ? "pages" : "posts";
      const requestBody = {
        title: post.title,
        content: post.content,
        status: post.status,
        categories: post.categories,
        tags: post.tags,
        featured_media: post.featured_media,
        excerpt: post.excerpt,
        slug: post.slug
      };
      console.log("WP Publisher - Creating post:", {
        endpoint,
        url: this.getApiUrl(endpoint),
        title: post.title,
        status: post.status,
        contentLength: (_a = post.content) == null ? void 0 : _a.length
      });
      const result = await this.request(endpoint, {
        method: "POST",
        body: JSON.stringify(requestBody)
      });
      console.log("WP Publisher - Response:", result);
      if (!result || !result.id) {
        console.error("WP Publisher - Invalid response:", result);
        return {
          success: false,
          error: "WordPress returned an invalid response (no post ID)"
        };
      }
      return {
        success: true,
        postId: result.id,
        postUrl: result.link
      };
    } catch (error) {
      console.error("WP Publisher - Error creating post:", error);
      return {
        success: false,
        error: error instanceof Error ? error.message : "Failed to create post"
      };
    }
  }
  /**
   * Update an existing post or page
   */
  async updatePost(postId, post) {
    try {
      const endpoint = post.type === "page" ? `pages/${postId}` : `posts/${postId}`;
      const result = await this.request(endpoint, {
        method: "PUT",
        body: JSON.stringify({
          title: post.title,
          content: post.content,
          status: post.status,
          categories: post.categories,
          tags: post.tags,
          featured_media: post.featured_media,
          excerpt: post.excerpt,
          slug: post.slug
        })
      });
      return {
        success: true,
        postId: result.id,
        postUrl: result.link
      };
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : "Failed to update post"
      };
    }
  }
  /**
   * Upload media (image) to WordPress
   */
  async uploadMedia(filename, data, mimeType) {
    try {
      const url = this.getApiUrl("media");
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "POST",
        headers: {
          "Authorization": this.authHeader,
          "Content-Type": mimeType,
          "Content-Disposition": `attachment; filename="${filename}"`
        },
        body: data,
        throw: false
      });
      if (response.status >= 400) {
        console.error("Media upload failed:", response.json);
        return null;
      }
      return response.json;
    } catch (error) {
      console.error("Media upload error:", error);
      return null;
    }
  }
  /**
   * Get a post by ID
   */
  async getPost(postId, type = "post") {
    try {
      const endpoint = type === "page" ? `pages/${postId}` : `posts/${postId}`;
      return this.request(endpoint);
    } catch (e) {
      return null;
    }
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  sites: [],
  defaultPostType: "post",
  defaultStatus: "draft",
  convertMarkdown: true,
  addFrontmatterOnPublish: true,
  uploadImages: true
};
var WPPublisherSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h1", { text: "WordPress Publisher Settings" });
    containerEl.createEl("h2", { text: "WordPress Sites" });
    containerEl.createEl("p", {
      text: "Add your WordPress sites. Use Application Passwords for authentication (Users \u2192 Profile \u2192 Application Passwords in WordPress).",
      cls: "setting-item-description"
    });
    new import_obsidian2.Setting(containerEl).setName("Add WordPress Site").setDesc("Configure a new WordPress site connection").addButton((button) => button.setButtonText("Add Site").setCta().onClick(() => {
      this.plugin.settings.sites.push({
        name: "My WordPress Site",
        url: "https://example.com",
        username: "",
        applicationPassword: "",
        isDefault: this.plugin.settings.sites.length === 0
      });
      this.plugin.saveSettings();
      this.display();
    }));
    this.plugin.settings.sites.forEach((site, index) => {
      const siteContainer = containerEl.createDiv({ cls: "wp-site-config" });
      siteContainer.createEl("h3", { text: `Site: ${site.name}` });
      new import_obsidian2.Setting(siteContainer).setName("Site Name").setDesc("A friendly name for this site").addText((text) => text.setPlaceholder("My Church Website").setValue(site.name).onChange(async (value) => {
        site.name = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian2.Setting(siteContainer).setName("Site URL").setDesc("Your WordPress site URL (e.g., https://www.mysite.com) - include www if your site uses it").addText((text) => text.setPlaceholder("https://www.example.com").setValue(site.url).onChange(async (value) => {
        site.url = value.replace(/\/$/, "");
        await this.plugin.saveSettings();
      }));
      new import_obsidian2.Setting(siteContainer).setName("Username").setDesc("Your WordPress username").addText((text) => text.setPlaceholder("admin").setValue(site.username).onChange(async (value) => {
        site.username = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian2.Setting(siteContainer).setName("Application Password").setDesc("Generate in WordPress: Users \u2192 Profile \u2192 Application Passwords").addText((text) => {
        text.setPlaceholder("xxxx xxxx xxxx xxxx xxxx xxxx").setValue(site.applicationPassword).onChange(async (value) => {
          site.applicationPassword = value;
          await this.plugin.saveSettings();
        });
        text.inputEl.type = "password";
      });
      new import_obsidian2.Setting(siteContainer).setName("Default Site").setDesc("Use this site by default when publishing").addToggle((toggle) => toggle.setValue(site.isDefault).onChange(async (value) => {
        this.plugin.settings.sites.forEach((s) => s.isDefault = false);
        site.isDefault = value;
        await this.plugin.saveSettings();
        this.display();
      }));
      new import_obsidian2.Setting(siteContainer).setName("Test Connection").addButton((button) => button.setButtonText("Test").onClick(async () => {
        button.setButtonText("Testing...");
        button.setDisabled(true);
        const client = new WordPressClient({
          siteUrl: site.url,
          username: site.username,
          applicationPassword: site.applicationPassword
        });
        const result = await client.testConnection();
        if (result.success) {
          new import_obsidian2.Notice(`\u2713 ${result.message}`);
        } else {
          new import_obsidian2.Notice(`\u2717 Connection failed: ${result.message}`);
        }
        button.setButtonText("Test");
        button.setDisabled(false);
      })).addButton((button) => button.setButtonText("Remove").setWarning().onClick(async () => {
        this.plugin.settings.sites.splice(index, 1);
        await this.plugin.saveSettings();
        this.display();
      }));
      siteContainer.createEl("hr");
    });
    containerEl.createEl("h2", { text: "Default Settings" });
    new import_obsidian2.Setting(containerEl).setName("Default Post Type").setDesc("Default content type when publishing").addDropdown((dropdown) => dropdown.addOption("post", "Post").addOption("page", "Page").setValue(this.plugin.settings.defaultPostType).onChange(async (value) => {
      this.plugin.settings.defaultPostType = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Default Status").setDesc("Default publish status").addDropdown((dropdown) => dropdown.addOption("draft", "Draft").addOption("publish", "Published").setValue(this.plugin.settings.defaultStatus).onChange(async (value) => {
      this.plugin.settings.defaultStatus = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Convert Markdown to HTML").setDesc("Convert Markdown syntax to HTML before publishing").addToggle((toggle) => toggle.setValue(this.plugin.settings.convertMarkdown).onChange(async (value) => {
      this.plugin.settings.convertMarkdown = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Update Frontmatter").setDesc("Add WordPress post ID and URL to note frontmatter after publishing").addToggle((toggle) => toggle.setValue(this.plugin.settings.addFrontmatterOnPublish).onChange(async (value) => {
      this.plugin.settings.addFrontmatterOnPublish = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Upload Images").setDesc("Upload embedded images to WordPress Media Library").addToggle((toggle) => toggle.setValue(this.plugin.settings.uploadImages).onChange(async (value) => {
      this.plugin.settings.uploadImages = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h2", { text: "Help" });
    containerEl.createEl("p", { text: "Use frontmatter in your notes to control publishing:" });
    const codeBlock = containerEl.createEl("pre");
    codeBlock.createEl("code", { text: `---
wp_post_type: post  # or 'page'
wp_status: draft    # or 'publish', 'pending', 'private'
wp_categories:      # category names
  - Announcements
  - Events
wp_tags:            # tag names
  - sunday-service
  - 2025
wp_excerpt: "A short description..."
wp_slug: custom-url-slug
wp_post_id: 123     # Set automatically after first publish
wp_post_url: https://... # Set automatically after publish
---` });
  }
};

// src/publish-modal.ts
var import_obsidian3 = require("obsidian");
var PublishModal = class extends import_obsidian3.Modal {
  constructor(app, plugin, file, content, frontmatter) {
    super(app);
    this.availableCategories = [];
    this.availableTags = [];
    this.isPublishing = false;
    this.plugin = plugin;
    this.file = file;
    this.content = content;
    this.frontmatter = frontmatter;
    const defaultSite = plugin.settings.sites.find((s) => s.isDefault) || plugin.settings.sites[0];
    this.options = {
      site: defaultSite,
      postType: frontmatter.wp_post_type || plugin.settings.defaultPostType,
      status: frontmatter.wp_status || plugin.settings.defaultStatus,
      categories: frontmatter.wp_categories || [],
      tags: frontmatter.wp_tags || [],
      title: frontmatter.wp_title || file.basename,
      excerpt: frontmatter.wp_excerpt || "",
      slug: frontmatter.wp_slug || ""
    };
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("wp-publisher-modal");
    contentEl.createEl("h2", { text: "Publish to WordPress" });
    if (this.plugin.settings.sites.length === 0) {
      contentEl.createEl("p", {
        text: "No WordPress sites configured. Please add a site in settings.",
        cls: "wp-publisher-warning"
      });
      new import_obsidian3.Setting(contentEl).addButton((btn) => btn.setButtonText("Open Settings").setCta().onClick(() => {
        this.close();
        this.app.setting.open();
      }));
      return;
    }
    const existingPostId = this.frontmatter.wp_post_id;
    if (existingPostId) {
      const existingNotice = contentEl.createDiv({ cls: "wp-publisher-notice" });
      existingNotice.createEl("span", { text: `\u{1F4DD} Updating existing ${this.options.postType} #${existingPostId}` });
    }
    if (this.plugin.settings.sites.length > 1) {
      new import_obsidian3.Setting(contentEl).setName("WordPress Site").addDropdown((dropdown) => {
        var _a;
        this.plugin.settings.sites.forEach((site) => {
          dropdown.addOption(site.url, site.name);
        });
        dropdown.setValue(((_a = this.options.site) == null ? void 0 : _a.url) || "");
        dropdown.onChange((value) => {
          this.options.site = this.plugin.settings.sites.find((s) => s.url === value);
          this.loadCategoriesAndTags();
        });
      });
    }
    new import_obsidian3.Setting(contentEl).setName("Title").addText((text) => text.setValue(this.options.title).onChange((value) => {
      this.options.title = value;
    }));
    new import_obsidian3.Setting(contentEl).setName("Post Type").addDropdown((dropdown) => dropdown.addOption("post", "Post").addOption("page", "Page").setValue(this.options.postType).onChange((value) => {
      this.options.postType = value;
      this.display();
    }));
    new import_obsidian3.Setting(contentEl).setName("Status").addDropdown((dropdown) => dropdown.addOption("draft", "Draft").addOption("publish", "Published").addOption("pending", "Pending Review").addOption("private", "Private").setValue(this.options.status).onChange((value) => {
      this.options.status = value;
    }));
    if (this.options.postType === "post") {
      new import_obsidian3.Setting(contentEl).setName("Categories").setDesc("Comma-separated category names").addText((text) => text.setPlaceholder("Announcements, Events").setValue(this.options.categories.join(", ")).onChange((value) => {
        this.options.categories = value.split(",").map((c) => c.trim()).filter((c) => c);
      }));
      new import_obsidian3.Setting(contentEl).setName("Tags").setDesc("Comma-separated tag names").addText((text) => text.setPlaceholder("sunday-service, 2025").setValue(this.options.tags.join(", ")).onChange((value) => {
        this.options.tags = value.split(",").map((t) => t.trim()).filter((t) => t);
      }));
    }
    new import_obsidian3.Setting(contentEl).setName("Excerpt").setDesc("Optional summary/description").addTextArea((textarea) => {
      textarea.setPlaceholder("A brief description of this content...").setValue(this.options.excerpt).onChange((value) => {
        this.options.excerpt = value;
      });
      textarea.inputEl.rows = 3;
    });
    new import_obsidian3.Setting(contentEl).setName("URL Slug").setDesc("Custom URL slug (optional)").addText((text) => text.setPlaceholder("my-custom-url").setValue(this.options.slug).onChange((value) => {
      this.options.slug = value;
    }));
    const buttonContainer = contentEl.createDiv({ cls: "wp-publisher-buttons" });
    new import_obsidian3.Setting(buttonContainer).addButton((btn) => btn.setButtonText("Cancel").onClick(() => this.close())).addButton((btn) => btn.setButtonText(existingPostId ? "Update" : "Publish").setCta().onClick(() => this.publish()));
  }
  async loadCategoriesAndTags() {
    if (!this.options.site)
      return;
    try {
      const client = new WordPressClient({
        siteUrl: this.options.site.url,
        username: this.options.site.username,
        applicationPassword: this.options.site.applicationPassword
      });
      this.availableCategories = await client.getCategories();
      this.availableTags = await client.getTags();
    } catch (error) {
      console.error("Failed to load categories/tags:", error);
    }
  }
  async publish() {
    if (this.isPublishing)
      return;
    this.isPublishing = true;
    const notice = new import_obsidian3.Notice("Publishing to WordPress...", 0);
    try {
      const result = await this.plugin.publishNote(
        this.file,
        this.content,
        this.frontmatter,
        this.options
      );
      notice.hide();
      if (result.success) {
        new import_obsidian3.Notice(`\u2713 Published successfully! Post ID: ${result.postId}`);
        this.close();
      } else {
        new import_obsidian3.Notice(`\u2717 Failed to publish: ${result.error}`);
      }
    } catch (error) {
      notice.hide();
      new import_obsidian3.Notice(`\u2717 Error: ${error instanceof Error ? error.message : "Unknown error"}`);
    }
    this.isPublishing = false;
  }
  display() {
    this.onOpen();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/markdown-converter.ts
function markdownToHtml(markdown) {
  let html = markdown;
  html = html.replace(/^######\s+(.+)$/gm, "<h6>$1</h6>");
  html = html.replace(/^#####\s+(.+)$/gm, "<h5>$1</h5>");
  html = html.replace(/^####\s+(.+)$/gm, "<h4>$1</h4>");
  html = html.replace(/^###\s+(.+)$/gm, "<h3>$1</h3>");
  html = html.replace(/^##\s+(.+)$/gm, "<h2>$1</h2>");
  html = html.replace(/^#\s+(.+)$/gm, "<h1>$1</h1>");
  html = html.replace(/\*\*\*(.+?)\*\*\*/g, "<strong><em>$1</em></strong>");
  html = html.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
  html = html.replace(/\*(.+?)\*/g, "<em>$1</em>");
  html = html.replace(/___(.+?)___/g, "<strong><em>$1</em></strong>");
  html = html.replace(/__(.+?)__/g, "<strong>$1</strong>");
  html = html.replace(/_(.+?)_/g, "<em>$1</em>");
  html = html.replace(/~~(.+?)~~/g, "<del>$1</del>");
  html = html.replace(/`([^`]+)`/g, "<code>$1</code>");
  html = html.replace(/```(\w*)\n([\s\S]*?)```/g, (match, lang, code) => {
    const langClass = lang ? ` class="language-${lang}"` : "";
    return `<pre><code${langClass}>${escapeHtml(code.trim())}</code></pre>`;
  });
  html = html.replace(/^>\s+(.+)$/gm, "<blockquote>$1</blockquote>");
  html = html.replace(/<\/blockquote>\n<blockquote>/g, "\n");
  html = html.replace(/^(-{3,}|\*{3,}|_{3,})$/gm, "<hr>");
  html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');
  html = html.replace(/!\[([^\]]*)\]\(([^)]+)\)/g, '<img src="$2" alt="$1">');
  html = html.replace(/^[\*\-]\s+(.+)$/gm, "<li>$1</li>");
  html = html.replace(/(<li>.*<\/li>\n?)+/g, "<ul>$&</ul>");
  html = html.replace(/^\d+\.\s+(.+)$/gm, "<li>$1</li>");
  html = html.replace(/^(?!<[a-z]|$)(.+)$/gm, "<p>$1</p>");
  html = html.replace(/<p><\/p>/g, "");
  html = html.replace(/\n\n+/g, "\n\n");
  return html.trim();
}
function escapeHtml(text) {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;");
}
function extractContent(content) {
  const frontmatterRegex = /^---\n([\s\S]*?)\n---\n?/;
  const match = content.match(frontmatterRegex);
  if (!match) {
    return { content, frontmatter: {} };
  }
  const frontmatterStr = match[1];
  const contentWithoutFrontmatter = content.slice(match[0].length);
  const frontmatter = {};
  const lines = frontmatterStr.split("\n");
  let currentKey = "";
  let currentArray = null;
  for (const line of lines) {
    const keyValueMatch = line.match(/^(\w+):\s*(.*)$/);
    const arrayItemMatch = line.match(/^\s+-\s+(.+)$/);
    if (keyValueMatch) {
      if (currentArray && currentKey) {
        frontmatter[currentKey] = currentArray;
      }
      currentKey = keyValueMatch[1];
      const value = keyValueMatch[2].trim();
      if (value === "") {
        currentArray = [];
      } else if (value === "true") {
        frontmatter[currentKey] = true;
        currentArray = null;
      } else if (value === "false") {
        frontmatter[currentKey] = false;
        currentArray = null;
      } else if (!isNaN(Number(value))) {
        frontmatter[currentKey] = Number(value);
        currentArray = null;
      } else {
        frontmatter[currentKey] = value.replace(/^["']|["']$/g, "");
        currentArray = null;
      }
    } else if (arrayItemMatch && currentArray !== null) {
      currentArray.push(arrayItemMatch[1].replace(/^["']|["']$/g, ""));
    }
  }
  if (currentArray && currentKey) {
    frontmatter[currentKey] = currentArray;
  }
  return { content: contentWithoutFrontmatter, frontmatter };
}
function updateFrontmatter(content, updates) {
  const { content: bodyContent, frontmatter } = extractContent(content);
  const newFrontmatter = { ...frontmatter, ...updates };
  const frontmatterLines = ["---"];
  for (const [key, value] of Object.entries(newFrontmatter)) {
    if (Array.isArray(value)) {
      frontmatterLines.push(`${key}:`);
      for (const item of value) {
        frontmatterLines.push(`  - ${item}`);
      }
    } else if (typeof value === "string" && value.includes(":")) {
      frontmatterLines.push(`${key}: "${value}"`);
    } else {
      frontmatterLines.push(`${key}: ${value}`);
    }
  }
  frontmatterLines.push("---");
  frontmatterLines.push("");
  return frontmatterLines.join("\n") + bodyContent;
}

// main.ts
var WPPublisherPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new WPPublisherSettingTab(this.app, this));
    this.addRibbonIcon("upload-cloud", "Publish to WordPress", () => {
      this.publishCurrentNote();
    });
    this.addCommand({
      id: "publish-current-note",
      name: "Publish current note to WordPress",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (file && file.extension === "md") {
          if (!checking) {
            this.publishCurrentNote();
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "publish-note-quick",
      name: "Quick publish (use defaults)",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (file && file.extension === "md") {
          if (!checking) {
            this.quickPublish();
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "publish-multiple-notes",
      name: "Publish selected notes",
      callback: () => {
        this.publishSelectedNotes();
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian4.TFile && file.extension === "md") {
          menu.addItem((item) => {
            item.setTitle("Publish to WordPress").setIcon("upload-cloud").onClick(() => {
              this.publishFile(file);
            });
          });
          menu.addItem((item) => {
            item.setTitle("Quick publish to WordPress").setIcon("zap").onClick(() => {
              this.quickPublishFile(file);
            });
          });
        }
        if (file instanceof import_obsidian4.TFolder) {
          menu.addItem((item) => {
            item.setTitle("Publish all notes to WordPress").setIcon("upload-cloud").onClick(() => {
              this.publishFolder(file);
            });
          });
        }
      })
    );
    console.log("WordPress Publisher loaded");
  }
  onunload() {
    console.log("WordPress Publisher unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Publish the currently active note
   */
  async publishCurrentNote() {
    const file = this.app.workspace.getActiveFile();
    if (!file) {
      new import_obsidian4.Notice("No active note to publish");
      return;
    }
    await this.publishFile(file);
  }
  /**
   * Open publish modal for a specific file
   */
  async publishFile(file) {
    const content = await this.app.vault.read(file);
    const { content: bodyContent, frontmatter } = extractContent(content);
    new PublishModal(this.app, this, file, bodyContent, frontmatter).open();
  }
  /**
   * Quick publish without modal (uses defaults/frontmatter)
   */
  async quickPublish() {
    const file = this.app.workspace.getActiveFile();
    if (!file) {
      new import_obsidian4.Notice("No active note to publish");
      return;
    }
    await this.quickPublishFile(file);
  }
  /**
   * Quick publish a specific file
   */
  async quickPublishFile(file) {
    if (this.settings.sites.length === 0) {
      new import_obsidian4.Notice("No WordPress sites configured. Please add a site in settings.");
      return;
    }
    const content = await this.app.vault.read(file);
    const { content: bodyContent, frontmatter } = extractContent(content);
    const defaultSite = this.settings.sites.find((s) => s.isDefault) || this.settings.sites[0];
    const options = {
      site: defaultSite,
      postType: frontmatter.wp_post_type || this.settings.defaultPostType,
      status: frontmatter.wp_status || this.settings.defaultStatus,
      categories: frontmatter.wp_categories || [],
      tags: frontmatter.wp_tags || [],
      title: frontmatter.wp_title || file.basename,
      excerpt: frontmatter.wp_excerpt || "",
      slug: frontmatter.wp_slug || ""
    };
    const notice = new import_obsidian4.Notice("Publishing to WordPress...", 0);
    const result = await this.publishNote(file, bodyContent, frontmatter, options);
    notice.hide();
    if (result.success) {
      new import_obsidian4.Notice(`\u2713 Published: ${options.title}`);
    } else {
      new import_obsidian4.Notice(`\u2717 Failed: ${result.error}`);
    }
  }
  /**
   * Publish multiple selected notes
   */
  async publishSelectedNotes() {
    const leaves = this.app.workspace.getLeavesOfType("file-explorer");
    if (leaves.length === 0) {
      new import_obsidian4.Notice("No files selected");
      return;
    }
    new import_obsidian4.Notice("Use the folder context menu to publish multiple notes");
  }
  /**
   * Publish all markdown files in a folder
   */
  async publishFolder(folder) {
    const files = folder.children.filter(
      (f) => f instanceof import_obsidian4.TFile && f.extension === "md"
    );
    if (files.length === 0) {
      new import_obsidian4.Notice("No markdown files in this folder");
      return;
    }
    const confirmed = await this.confirmBulkPublish(files.length);
    if (!confirmed)
      return;
    let successCount = 0;
    let failCount = 0;
    for (const file of files) {
      try {
        await this.quickPublishFile(file);
        successCount++;
      } catch (e) {
        failCount++;
      }
    }
    new import_obsidian4.Notice(`Published ${successCount} notes, ${failCount} failed`);
  }
  /**
   * Confirm bulk publish operation
   */
  async confirmBulkPublish(count) {
    return new Promise((resolve) => {
      const notice = new import_obsidian4.Notice(`Publish ${count} notes to WordPress? Click to confirm.`, 1e4);
      notice.noticeEl.onclick = () => {
        notice.hide();
        resolve(true);
      };
      setTimeout(() => resolve(false), 1e4);
    });
  }
  /**
   * Main publish logic
   */
  async publishNote(file, content, frontmatter, options) {
    const client = new WordPressClient({
      siteUrl: options.site.url,
      username: options.site.username,
      applicationPassword: options.site.applicationPassword
    });
    let htmlContent = content;
    if (this.settings.convertMarkdown) {
      htmlContent = markdownToHtml(content);
    }
    const categoryIds = [];
    const tagIds = [];
    if (options.postType === "post") {
      for (const catName of options.categories) {
        try {
          const cat = await client.getOrCreateCategory(catName);
          categoryIds.push(cat.id);
        } catch (e) {
          console.error(`Failed to get/create category: ${catName}`, e);
        }
      }
      for (const tagName of options.tags) {
        try {
          const tag = await client.getOrCreateTag(tagName);
          tagIds.push(tag.id);
        } catch (e) {
          console.error(`Failed to get/create tag: ${tagName}`, e);
        }
      }
    }
    const post = {
      title: options.title,
      content: htmlContent,
      status: options.status,
      type: options.postType,
      categories: categoryIds.length > 0 ? categoryIds : void 0,
      tags: tagIds.length > 0 ? tagIds : void 0,
      excerpt: options.excerpt || void 0,
      slug: options.slug || void 0
    };
    const existingPostId = frontmatter.wp_post_id;
    const isValidPostId = typeof existingPostId === "number" && existingPostId > 0;
    console.log("WP Publisher - Post ID check:", { existingPostId, isValidPostId, type: typeof existingPostId });
    let result;
    if (isValidPostId) {
      result = await client.updatePost(existingPostId, post);
    } else {
      result = await client.createPost(post);
    }
    if (result.success && this.settings.addFrontmatterOnPublish) {
      const originalContent = await this.app.vault.read(file);
      const updatedContent = updateFrontmatter(originalContent, {
        wp_post_id: result.postId,
        wp_post_url: result.postUrl,
        wp_last_published: new Date().toISOString().split("T")[0]
      });
      await this.app.vault.modify(file, updatedContent);
    }
    return result;
  }
};
